# Sidebar navigation

- label: "Introduction"
  link: "/"
- label: Atoms
  items:
    - label: "Button"
      link: "/Components/Atoms/Button"
    - label: "Close Button"
      link: "/Components/Atoms/CloseButton"
    - label: "Input"
      link: "/Components/Atoms/Input"
    - label: "Textarea"
      link: "/Components/Atoms/Textarea"
    - label: "Label"
      link: "/Components/Atoms/Label"
    - label: "Spinner"
      link: "/Components/Atoms/Spinner"
    - label: "ThemeToggle"
      link: "/Components/Atoms/ThemeToggle"
- label: "Utilities"
  items:
    - label: "Smart Outline"
      link: "/Utilities/SmartOutline"

- label: Community
  items:
    - label: "Github"
      link: https://github.com/bulbariss/ui
